### PR TITLE
Refactor for packaging

### PR DESCRIPTION
**Pull request by jeffbyrnes**
The commits tell the tale, but some summary:

* Add config & adjust scripts so this can be installed directly from NPM.js or another repository, and used as a shell command
* Improve readability of the README when viewed as plain text
* Drop useful, but easily outdated, macOS scripts in favor of pointing folks directly to [Nodejs.org](https://Nodejs.org)
* Update dependencies & add `engines` config
* Add EditorConfig & clean up whitespace per typical JavaScript/Node.js community conventions

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
@justiceserv happy to help you publish this to NPMjs.org if you’ve never done that. Thanks for writing this, it works great!

**Comment by justiceserv** [comment]
Sorry for late reply, I was a bit busy this week. 
I will start looking at your branch!

**Comment by justiceserv** [comment]
I checked your commit, thanks for your wonderful job! 
I merged this to master. 
Awesome job! 
Thanks for your contribution :D

**Comment by jeffbyrnes** [comment]
@justiceserv you’re welcome!

**Comment by jeffbyrnes** [comment]
Glad to see you’ve already published it!

**Pull request merged**
